### ISSUE TITLE
sixtel with tmux 3.4 no image is shown

### ISSUE THREAD

**Issue by step-** [bakkeby/st-flexipatch#111]
I updated to tmux 3.4, which supports sixel images when compiled with --enable-sixel. It appears that st-flexipatch with SIXTEL_PATCH shows an empty rectangle instead of an image. I read all open and closed sixtel issues on https://github.com/tmux/tmux/issues but I couldn't find a solution.
I applied all the points they mention:
- image size less that 1 MB
- small dimensions
- tmux.conf `set-options -as terminal-features ',st-256color:sixtel'`.

I tested several sixtel images downloaded from the issues pages.  Sixtel support works outside tmux with TERM=st-256color but doesn't work when tmux is running with inside TERM=tmux-256color.
My patches.h file is attached.

So I wonder if anyone could please test st-flexipatch with tmux 3.4 and confirm if sixtel images work for them. Thank you.

[patches.h.txt](https://github.com/bakkeby/st-flexipatch/files/14436518/patches.h.txt)

left: st outside tmux;         right: st running tmux

![st-sixtel-20240228](https://github.com/bakkeby/st-flexipatch/assets/1414102/07cad597-06f8-4deb-b67e-1ce933e5191f)

**Comment by bakkeby** [comment]
Hi @step-,

can you try @veltza's [st-sx](https://github.com/veltza/st-sx) build?

It has quite a few improvements when it comes to sixel support and it may potentially work there.

**Comment by step-** [comment]
Hi @bakkeby, thanks. Tried and yes, sixtel inside tmux works in st-sx.

**Comment by bakkeby** [comment]
Right, OK. The plan is to integrate those changes into st-flexipatch ref. #102.
