### ISSUE TITLE
Externalpipe patch not working with the reflow patch

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/st-flexipatch#122]
I noticed that both of these patches don't work together.

## Steps to reproduce
1. Get source: https://github.com/UtkarshVerma/st-flexipatch
2. Compile and run.
3. Invoking externalpipe should cause segfault. (Press `<Ctrl><Shift>u` or `<LAlt>u`.

**Comment by step-** [comment]
Related: gcc warns about a pointer from integer cast in patch/externalpipe.c.
* [gcc.txt](https://github.com/bakkeby/st-flexipatch/files/14598534/gcc.txt) 
* [patches.h.txt](https://github.com/bakkeby/st-flexipatch/files/14598701/patches.h.txt)

 
(The linker error in the log file is probably unrelated to the current issue. I still need to investigate that.)

**Comment by bakkeby** [comment]
It seems to just be that one line that was causing issues. Can you let me know if this solved it for you?

**Comment by UtkarshVerma** [comment]
Thanks for the quick fix. It works now.
