### ISSUE TITLE
Feature request: Right Click Paste patch

### ISSUE THREAD

**Issue by og900aero** [bakkeby/st-flexipatch#133]
If you think so too, please make the RighTClickPaste patch available as well. Thank u.

[]https://st.suckless.org/patches/rightclickpaste/

**Comment by bakkeby** [comment]
Hmm, but it is like a one character config change. 

https://st.suckless.org/patches/rightclickpaste/st-rightclickpaste-0.9.diff

**Comment by og900aero** [comment]
Okay, then not.
