### ISSUE TITLE
Patch request: anygeometry

### ISSUE THREAD

**Issue by FeodorPetrov** [bakkeby/st-flexipatch#137]
Could you please add patch https://st.suckless.org/patches/anygeometry/ support?
I tryed to patch it manualy, but I either got a segmentation fault either requested geometry does not apply.

**Comment by bakkeby** [comment]
I don't know. The writeup of that patch doesn't make much sense, it takes about tiling window managers, but everything about it suggests that it is all about specifying an exact size when having it as a floating window. 

What are you trying to achieve?

You may also want to consider `ANYSIZE_SIMPLE_PATCH`.

**Comment by FeodorPetrov** [comment]
I need to launch st fullscreen.

**Comment by bakkeby** [comment]
I see. The anygeometry patch wouldn't actually help you achieve that though.

There is the fullscreen patch for st, but it is only toggle-able after the terminal window has opened. I suppose that it would be possible to have a command line flag that sets the _NET_WM_STATE_FULLSCREEN property for the window before it is mapped - indicating to the window manager that it wants to be opened in fullscreen.

That would depend on the window manager actually respecting that property though.

Another alternative would be to have the window manager trigger fullscreen for the window based on client rules. I have something like that but I don't think there is an example patch around for dwm to do that.

**Comment by FeodorPetrov** [comment]
By "fullscreen" I mean opened maximaly to screen borders.
Now I use original st with anygeometry patch to launch it maximized (-G 1366x768) to screen resolution. For now I don't have a WM on my CRUX (but I'm going to install, but didn't yet decided which), and if the terminal window isn't maximized, if the mouse cursor is located outside the terminal window -- input from keybord does not work for the terminal. That's why I need the terminal to be maximized. I dont know how to achieve this whithout this patch. Though what you say about "fullscreen patch" makes sense.

**Comment by bakkeby** [comment]
A WM-less build. I'm impressed.

I can see the anygeometry patch being the right choice in this situation. I'll have a look to see if it can be integrated.

**Comment by bakkeby** [comment]
There you go, I did some testing and it seemed to work just fine. Let me know if you have any trouble with it.

**Comment by FeodorPetrov** [comment]
Thanks! Will check the day after tomorrow.

**Comment by FeodorPetrov** [comment]
everything works fine!

**Comment by bakkeby** [comment]
Very good, I'll just mark this as closed.
