### ISSUE TITLE
Unable to `make` while using scrollback patch

### ISSUE THREAD

**Issue by smhmd** [bakkeby/st-flexipatch#14]
![image](https://user-images.githubusercontent.com/46059092/112761983-a1d85180-8ff5-11eb-8109-2357bef7bba8.png)

Reproduce:
- Clone the repo.
- Enable `SCROLLBACK_PATCH` (line `191`)
- Run `make`.

Error:
```java
In file included from st.c:20:
st.h:133:12: error: ‘HISTSIZE’ undeclared here (not in a function)
  133 |  Line hist[HISTSIZE]; /* history buffer */
      |            ^~~~~~~~
make: *** [Makefile:32: st.o] Error 1
```

**Comment by bakkeby** [comment]
Thanks! That was caused by the sixel refactoring.
