### ISSUE TITLE
Distinguish between tab and ctrl-i

### ISSUE THREAD

**Issue by mohammad-amin-khajeh** [bakkeby/st-flexipatch#144]
Currently `tab` and `ctrl-i` are seen as the same key by the shell which IS the default behavior.
However some terminals like alacritty have the ability to distinguish between them and turn them them separate inputs.

In neovim I have bound `tab` to go to the next buffer, which indirectly also bounds `ctrl-i`, the problem is that `ctrl-i` is used for going up the jumplist which has nothing to do with the opened buffers but I can't have them both bound to different things at the same time due to the limitations of the shell.

It would be nice if st could see them as separate inputs like alacritty.
For reference, this is how alacritty does it: `{ key: I, mods: Control, chars: "\x1b[105;6u" }`

**Comment by bakkeby** [comment]
It looks like this is merely configuration.

You could add a new entry in the `key` array, e.g.

```diff
 /*
  * This is the huge key array which defines all compatibility to the Linux
  * world. Please decide about changes wisely.
  */
 static Key key[] = {
 	/* keysym           mask            string      appkey appcursor */
 	{ XK_KP_Home,       ShiftMask,      "\033[2J",       0,   -1},
 	...
 	{ XK_Next,          ShiftMask,      "\033[6;2~",     0,    0},
 	{ XK_Next,          XK_ANY_MOD,     "\033[6~",       0,    0},
+	{ XK_i,             ControlMask,    "\033[105;6u",   0,    0},
 	{ XK_F1,            XK_NO_MOD,      "\033OP" ,       0,    0},
 	{ XK_F1, /* F13 */  ShiftMask,      "\033[1;2P",     0,    0},
 	...
```

but if you do this then you also need to add `XK_i` to the `mappedKeys` array.

```diff
 /*
  * If you want keys other than the X11 function keys (0xFD00 - 0xFFFF)
  * to be mapped below, add them to this array.
  */
-static KeySym mappedkeys[] = { -1 };
+static KeySym mappedkeys[] = { XK_i };
```

There is also the [fix keyboard input](https://st.suckless.org/patches/fix_keyboard_input/) patch for st which binds an escape code similar to yours.

https://github.com/bakkeby/st-flexipatch/blob/7a581fe4e15b538d3440562aa7f89d775187f250/patch/fixkeyboardinput.c#L563

In practice there is no difference between `\x1b` and `\033` as they are the same value (the first is hex and the second is octal, both being decimal 27).

**Comment by mohammad-amin-khajeh** [comment]
Thanks for the clear explanation!
Closing the issue.
