### ISSUE TITLE
osc133 can't scroll to prompt

### ISSUE THREAD

**Issue by step-** [bakkeby/st-flexipatch#152]
Hi, thanks to the author of PR #127 and everyone involved there who helped to create this new feature; I've always wanted to be able to jump back through prompts with ease. Unfortunately, I can't get it to work but it must be me.

This is my current prompt set with a zsh precmd function, and captured from `st -o - | xxd` after pressing Enter a few times.

```
00000260: 1b3d 1b5b 3f32 3030 3468 1b5b 3f31 6c1b  .=.[?2004h.[?1l.
00000270: 3e1b 5b3f 3230 3034 6c0d 0d0a 1b5b 316d  >.[?2004l....[1m
00000280: 1b5b 376d 231b 5b32 376d 1b5b 316d 1b5b  .[7m#.[27m.[1m.[
00000290: 306d 2020 2020 2020 2020 2020 2020 2020  0m              
000002a0: 2020 2020 2020 2020 2020 2020 2020 2020                  
000002b0: 2020 2020 2020 2020 2020 2020 2020 2020                  
000002c0: 2020 2020 2020 2020 2020 2020 2020 2020                  
000002d0: 2020 2020 2020 2020 2020 2020 2020 2020                  
000002e0: 200d 200d 2d1b 5d30 3b20 2072 6f6f 7407   . .-.]0;  root.
000002f0: 1b5d 3133 333b 411b 5c0d 1b5b 306d 1b5b  .]133;A.\..[0m.[
00000300: 3237 6d1b 5b32 346d 1b5b 4a1b 5b31 6d1b  27m.[24m.[J.[1m.
00000310: 5b33 356d 1b5b 376d 7e1b 5b32 376d 1b5b  [35m.[7m~.[27m.[
00000320: 316d 20e2 99af 201b 5b4b 1b5b 3f31 681b  1m ... .[K.[?1h.
```

The bytes from the start to "root." included display `$PWD` in st's window title, then comes the ocs133 sequence, then a colorized `PROMPT`, which ends with a UTF-8 encoded unicode codepoint (0xE299AF), a space, and ANSI color resets.
When I press Ctrl+PgUp the terminal scrolls to the first buffer line, regardless there is or isn't a previous `PROMPT` on that line (tested by running `seq 200000` to ensure there are more lines than the buffer can hold). With Ctrl+PgDown the terminal scrolls to the last buffer line. I'm positive that the function this patch binds to Ctrl+PgUp/Down is called (tested by changing the function from `scrolltopos` to `newterm` and observing new terminals opening when I press those keys). Any idea what could be the reason the terminal doesn't scroll through previous prompts?

**Comment by step-** [comment]
PS Off topic but probably issue #126 can be closed.

**Comment by veltza** [comment]
Hard to see how you are configuring your shell prompt. But whatever kind of prompt you use, technically it should work when you prefix your prompt with the OSC 133 sequence like this:

Bash:

```
PS1='\[\033]133;A\007\]'$PS1
```

Zsh:

```
PROMPT=$'%{\e]133;A\a%}'$PROMPT
```

Try this on the default shell prompt first and when you know it works, try adding it to your own prompt.

**Comment by veltza** [comment]
The [specification](https://gitlab.freedesktop.org/Per_Bothner/specifications/blob/master/proposals/semantic-prompts.md) implies that the OSC 133 sequence ends with BEL, but ST (String Terminator) should work as well.

I've also had trouble getting it to work reliably with precmd, so I've found that it's guaranteed to work when you put it directly into the prompt.

**Comment by step-** [comment]
Thank you so much.

**Comment by bakkeby** [comment]
The foot wiki used `\e]133;A\e\\` as you say. That didn't work for me either unless I put another pair of backslashes at the end (`\e]133;A\e\\\\`). Using `\007` (BEL) or `\134` (backslash) seems like a better solution.
