### ISSUE TITLE
boxdraw patch doesnt work

### ISSUE THREAD

**Issue by og900aero** [bakkeby/st-flexipatch#160]
I try boxdraw patch for smooth line, but doesnt work:

![screenshot_1733835141](https://github.com/user-attachments/assets/1302d914-6bd1-4d1b-b969-e406fc4a1f4d)

**Comment by avih** [comment]
It's disabled by default. You need to enable the boxes/bold/braille at your `config.h`, here: https://github.com/bakkeby/st-flexipatch/blob/b77fb11b7664b82cefcaaa21a7f4b0faa48775b0/config.def.h#L127-L137

**Comment by og900aero** [comment]
Yoo-hoo, working fine. Thx!
