### ISSUE TITLE
Add new patch that is not included

### ISSUE THREAD

**Issue by dumrich** [bakkeby/st-flexipatch#17]
I am trying to install the Nord Theme patch, but it doesn't seem to be working. How can I use st-flexipatch to install the Nord theme, or any other patch that is not included?

**Comment by bakkeby** [comment]
All of the different "theme" patches are non-functional - they are just changing colour settings.

It is easy enough to look at the diff and apply the changes manually:
https://st.suckless.org/patches/nordtheme/st-nordtheme-0.8.2.diff

https://github.com/bakkeby/st-flexipatch/blob/c3ed7be89326918e3affa2909986d3f9c69732d1/config.def.h#L133-L162

As for other patches that are not included - you are either out of luck or add a request to have them added, or try patching by hand.
