### ISSUE TITLE
Blinking cursor patch?

### ISSUE THREAD

**Issue by Barbarossa93** [bakkeby/st-flexipatch#20]
First of all, thank you for this! As someone not too comfortable with C this is a great starting point/reference for working with st.
The only thing I miss is having a blinking cursor. Is this possible to include?

**Comment by Barbarossa93** [comment]
I just browsed through the patches on suckless's website. Another nice patch would be [undercurl](https://st.suckless.org/patches/undercurl/).

**Comment by bakkeby** [comment]
Just to note there may be a conflict between the [undercurl](https://st.suckless.org/patches/undercurl/) and [vertcenter](https://st.suckless.org/patches/vertcenter/) patches.

**Comment by Barbarossa93** [comment]
Wow, that was fast! Thank you!
