### ISSUE TITLE
[patch request] Here is a list of the patches that should be included in the project

### ISSUE THREAD

**Issue by NNBnh** [bakkeby/st-flexipatch#21]
Hello and first of, thank you so much for create this awesome project, without this i will never even thinking about using of patching ST. But there are some patches that i think should be included in the project:

### ANSI escape sequences
  > [ANSI escape sequences](https://en.wikipedia.org/wiki/ANSI_escape_code) (e.g: [OSC](https://en.wikipedia.org/wiki/ANSI_escape_code#OSC_(Operating_System_Command)_sequences) and [SGR](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR) parameters) are the standard that all terminal should supported, it's enable some tool such as [`bui-terminal`](https://github.com/NNBnh/bui-terminal) to handle changing color scheme on-the-fly  (doesn't need to restart the terminal) and cross-terminal without having to config individual terminal (some of which doesn't support xresources).
- [x] [`blinking_cursor`](https://st.suckless.org/patches/blinking_cursor) *(mentioned in #20)*: to control cursor's look
- [x] [`osc_10_11_12_2`](https://st.suckless.org/patches/osc_10_11_12_2): change terminal's colorscheme
- [x] ~~[`xclearwin`](https://st.suckless.org/patches/xclearwin): clears the window before the redraw of the terminal when the bg color has been changed~~ *(merged)*
- [x] [`undercurl`](https://st.suckless.org/patches/undercurl) *(mentioned in #20)*: support for special underlines

### Desktop icon
- [x] [`desktopentry`](https://st.suckless.org/patches/desktopentry): creates a desktop-entry for st. This enables to find st in a graphical menu and to display it with a nice icon
- [x] [`netwmicon`](https://st.suckless.org/patches/netwmicon): enables to set *_NET_WM_ICON* which hardcodes an icon for st:
  > Generally the icon of an application is defined by its desktop-entry. A patch with the name [`desktopentry`](https://st.suckless.org/patches/desktopentry) already exists for this purpose. However, some programs like tint2 do not respect the desktopentry and rely instead on an hardcoded icon which has to be defined by *_NET_WM_ICON*. Since st does not define *_NET_WM_ICON* those programs will display some default icon (which is ugly).

### Rendering
- [x] [`sync`](https://st.suckless.org/patches/sync): better draw timing to reduce flicker/tearing and improve animation smoothness

### Inputs
- [x] [`delkey`](https://st.suckless.org/patches/delkey): return BS on pressing backspace and DEL on pressing the delete key
- [x] [`universcroll`](https://st.suckless.org/patches/universcroll): always use Mouse{4,5} to scroll {Up,Down}. Doesn't matter alt screen or not. No more `^Y^Y^Y^Y^Y^E^E^E^E^E`!

### Extra
  > Features that can be achieved through using terminal multiplexers or other utility.
- [x] [`vim_browse`](https://st.suckless.org/patches/vim_browse): move through the terminal history-buffer, search for strings using VIM-like motions, operations and quantifiersdelete key

**Comment by bakkeby** [comment]
xclearwin looks to have been merged upstream.

**Comment by Barbarossa93** [comment]
It seems that the copyurl patch can't handle non-ascii characters, which is problematic for irc clients such as weechat. Looks like there's a [patch](https://git.suckless.org/sites/commit/d1335e5ce2a14ffd8e3e3161098d2263cccef1a7.html) that works around this. Would it be possible to include this?  My guess would be that this would require re-implementing the patch that's already there?

**Comment by Barbarossa93** [comment]
Actually, I literally just replaced the copyurl.c patch. Works great! Want me to make a PR?

**Comment by Barbarossa93** [comment]
Out of curiousity, what are your thoughts on the [vim browse](https://st.suckless.org/patches/vim_browse/) patch? As a user of vim keybindings, I think this would be far superior alternative to the keyboard select patch

**Comment by NNBnh** [comment]
> Actually, I literally just replaced the relevant part of copyurl.c patch. Works great! Want me to make a PR?

Sound great!

> Out of curiousity, what are your thoughts on the [vim browse](https://st.suckless.org/patches/vim_browse/) patch? As a user of vim keybindings, I think this would be far superior alternative to the keyboard select patch

The patch look really cool, but because most of it's feature can be achieved through using a terminal multiplexers like [Tmux](https://github.com/tmux/tmux/wiki), i will add this patch to the extra section.

**Comment by bakkeby** [comment]
@Barbarossa93, is the [vim browse](https://st.suckless.org/patches/vim_browse/) patch something you actually use? Have you even tried it?

**Comment by Barbarossa93** [comment]
I tried messing around with it on a clean st, but it's a bit hard to say how useful it'll be without the other patches (such as clipboard). The big reason I suggested it is because I'm using the keyboard select patch and I find myself getting annoyed that I can't use actual vim keybindings. I guess the alternative would be to modify the keyboard select patch to more closely match vim, but even then the behavior wouldn't be quite vim like. I do REALLY like the search history buffer with the vim browse patch though, that's already a major improvement over the keyboard select patch.

By the way, thanks for updating the copyurl patch! :)

**Comment by bakkeby** [comment]
It is worth noting that the [sync](https://st.suckless.org/patches/sync/) patch alters st.info to advertise that the terminal supports extra escape sequences for synchronized updates (or at least that's what I think it means).

I am not aware of any good way to control this using pre-processors, so it is enabled by default. In principle this could give misbehaviour if one is not using the patch and e.g. tmux is led to believe that there is support when there really isn't. 

I'll leave this on for now, but if this is actually causing issues for people then maybe users will end up having to uncomment lines in st.info as well (like one is currently required to do for some changes in config.mk or Makefile).

**Comment by bakkeby** [comment]
The vim browse patch was rather annoying to integrate, but it is there. There is something that is not quite right though and so far I have not been able to figure it out. The overlay highlights that appear in both https://github.com/juliusHuelsmann/st-history-vim and if you apply the patch on a bare st 0.8.4 do not appear in dwm-flexipatch. Could have something to do with the colors, but needs some testing and debugging. If it doesn't work then I may have to roll this back.

**Comment by Barbarossa93** [comment]
Uh oh, it seems that the vim browse patch has a bug. If I try to yank some selection, st segfaults. Looks like it was fixed [upstream](https://github.com/juliusHuelsmann/st-history-vim/issues/14). 

I just tried the fix myself and it was super simple. You just need to comment/remove line 208 in `x.c`. May as well remove that if-else block as well

**Comment by bakkeby** [comment]
There's an `xsetsel(getsel());` in keyboardselect and copyurl patches as well, would be good to test those as well.

**Comment by bakkeby** [comment]
Sorted the vim-browse issue, it was a missing line `historyOverlay(x, y1, &new);` in the `xdrawline` function. I included this when applying the patch, but missed that there are two versions of the code depending on whether wide glyphs are enabled or not. This should be sorted now. The flexipatch finalizer was helpful in spotting this.

**Comment by NNBnh** [comment]
Look like everythings is done, great work!

**Comment by bakkeby** [comment]
It is also worth noting that that alpha-focus-highlight patch, by the same guy who did the vim-browse patch, is really awesome. If you use the alpha patch then you owe it to yourself to try it out.
