### ISSUE TITLE
swapmouse patch?

### ISSUE THREAD

**Issue by Barbarossa93** [bakkeby/st-flexipatch#28]
Sorry to make intermittent requests, but I was wondering if you'd be willing to implement the [swapmouse](https://st.suckless.org/patches/swapmouse/) patch?

**Comment by bakkeby** [comment]
Such a simple patch. The main trickery was getting this to work with the [hidecursor](https://st.suckless.org/patches/hidecursor/) patch.

**Comment by Barbarossa93** [comment]
Awesome, thanks! :D
