### ISSUE TITLE
Patch Request: font2

### ISSUE THREAD

**Issue by smhmd** [bakkeby/st-flexipatch#3]
Would like to request this patch. Thanks.
https://st.suckless.org/patches/font2/

**Comment by bakkeby** [comment]
Hi @smhmd,

I have added this now. It compiles and runs fine, but I didn't have a practical test case to confirm that it works as intended.

\\
Thanks,

-Stein

**Comment by smhmd** [comment]
I forgot to reply to you. It works great.
