### ISSUE TITLE
click url patch?

### ISSUE THREAD

**Issue by Barbarossa93** [bakkeby/st-flexipatch#32]
I was interesting in trying to implement a click url method as I wasn't really a fan of having to put the link in my clipboard history before being able to right click the link (through the right click to plumb patch). With a cursory google search, I stumbled across [this](https://www.reddit.com/r/suckless/comments/cc83om/st_open_url/) reddit post. Would you be willing to include the patch provided in the post with this repo? If not, no big deal; it was pretty easy to include myself.

**Comment by bakkeby** [comment]
The patch seems to work fine, would be nice though if the URLs were underlined when you hover the mouse cursor over them like in Alacritty.

**Comment by Barbarossa93** [comment]
Yeah, it's unfortunate that it doesn't underline. I'm just happy I don't have to clog my clipboard history with links now.

Thanks for including the patch!
