### ISSUE TITLE
Unicode characters not displayed when ncmpcpp-ueberzug is opened directly with a dwm keybind

### ISSUE THREAD

**Issue by godspeedfw** [bakkeby/st-flexipatch#40]
I have binded [ncmpcpp-uezberg](https://github.com/alnj/ncmpcpp-ueberzug) to a key in my dwm config (`static const char *music[] = {"st", "-e" , "/home/sophos/.config/ncmpcpp/ncmpcpp-ueberzug/ncmpcpp-ueberzug"};`). When I use this keybinding unicode characters aren't displayed. 
![image](https://user-images.githubusercontent.com/74945202/129450145-e7167c74-7577-4bd9-99e5-5e0ec4c8b13c.png)
Left window is how it should look, right window is how it looks when opened with the keybind.
This doesn't happen when I open the terminal first and then enter the command. It also doesn't happen if I open it using the command `st -e /home/sophos/.config/ncmpcpp/ncmpcpp-ueberzug/ncmpcpp-ueberzug` either. It works fine with normal ncmpcpp.
It works as it should on alacritty.

**Comment by bakkeby** [comment]
Have you ever worked with cron jobs before?

A shell script may work perfectly fine from the command line, but not work at all when run as a cron job. This has to do with that environment variables, the path, aliases, etc. is not the same when the script is run via the cron job compared to when it is run from the command line.

I suspect that you have a similar issue in this context, that some environment variables are not the same when spawning the command via a dwm keybinding compared to when you execute st via the command line.

Not sure what the best way to check this would be, but perhaps comparing a command like this when launched as a dwm keybinding vs from the command line:
```sh
st -e sh -c 'env; sh'
```

It might be the `LC_ALL` environment variable, not sure.

As for how to set this I guess try adding this in your ~/.xinitrc if you are not using a login manager and in ~/.xsession if you are.

**Comment by godspeedfw** [comment]
I cant get `st -e sh -c 'env; sh'` to run using a keybinding. The terminal window closes as soon as I press the keys.
I tried `static const char *test[] = {"st", "-e" ,"sh", "-c", "'env; sh'"};` and `static const char *test[] = {"st", "-e" ,"sh -c 'env; sh'"};`

**Comment by godspeedfw** [comment]
`LC_ALL` was it! I set `LC_ALL="en_US.UTF-8"` in xinitrc and it worked perfectly.
Also, can you tell me what's the proper way to make those keybinds? Should I have each command and flag separated by commas? How am I supposed to do it?

**Comment by bakkeby** [comment]
So the command on the terminal is

```sh
st -e sh -c 'env; sh'
```

and on the terminal the command and each argument are separated by spaces. Here the single, or double for that matter, quotes means that the `env; sh` bit is a single parameter. 

When it comes to the command string arrays the command and each argument are separated by commas.

As such I would think the array would look like this:

```c
static const char *test[] = {"st", "-e", "sh", "-c", "env; sh"};
```
That is, `env; sh` being without extra quotes in this context as the commas separate the arguments. 

That said I'm on mobile and haven't tested the above so can't guarantee that it will work.

In general I would recommend using [sxhkd](https://github.com/baskerville/sxhkd) for application keybindings though. Besides that you can change them without having to recompile your window manager it is also convenient in that your application keybindings stay the same even if you try out someone else's build or another window manager.

Also if I have a more complicated command with multiple command line arguments etc. then I find it a lot more convenient to just dump the command(s) in a shell script and make a keybinding for the shell script instead. It simplifies things if I need to tweak the command later and I do not have to fiddle around to work out what the correct signature is to make the command work when I add it as a command within dwm.

**Comment by godspeedfw** [comment]
> `static const char *test[] = {"st", "-e", "sh", "-c", "env; sh"};`

Yeah, that worked. You're right, I will start using sxhkd for application shortcuts. It seems way better.
Also, I tried running that command from the dwm keybind and the `LC_ALL` variable is same. I thought it's because I hadn't removed the env variable from xinitrc but it's still fine even after I removed it. Unicode characters somehow display correctly after just setting the variable once and then removing it. Maybe it ends up being persistent somehow?

**Comment by bakkeby** [comment]
The `LC_ALL` environment variable you set in your ~/.xinitrc would stay until the X session ends.

I would have thought that after restarting your computer it would go back to what it was before.

**Comment by godspeedfw** [comment]
I started another X session in a different tty. Would it still stay same?

**Comment by bakkeby** [comment]
I don't think so, but perhaps it depends on whether the `LC_ALL` environment variable is set in the tty itself nor not.

**Comment by godspeedfw** [comment]
It is set in tty but then why was this issue arising before?

**Comment by bakkeby** [comment]
That I don't know. Is it set when you restart your computer?

**Comment by godspeedfw** [comment]
It's there even after restarting.

**Comment by bakkeby** [comment]
Who knows. 

Could of course be that something else changed and that it wasn't the `LC_ALL` environment variable that caused your issues when spawning via dwm in the first place. 

If you explicitly unset the environment variable in the tty before starting dwm can you still reproduce the issue?

**Comment by godspeedfw** [comment]
I can't. Though my fonts and colors break in st if I do that.

**Comment by godspeedfw** [comment]
~I can't. Though my fonts and colors break in st if I do that.~
I'm sorry. That was just me messing up my xresources somehow. Completely unrelated.

It works properly even after I explicitly unset the environment variable in the tty. 
I just had to run st with the variable set once and the issue doesn't arise after that.

**Comment by bakkeby** [comment]
I'll mark this as closed.
