### ISSUE TITLE
How to preserve scrollback buffer on `Ctrl+l`. 

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/st-flexipatch#46]
Most terminals(e.g. Alacritty) have this thing where pressing `Ctrl + l` only scrolls the shell prompt to the top, while keeping the scrollback history.

In `st`, however, this keybinding clears the scrollback buffer as well. As it's not to my preference, could you please let me know which section of the code should I look into?

**Comment by bakkeby** [comment]
Hi @UtkarshVerma,

it looks to be these lines of code.
https://github.com/bakkeby/st-flexipatch/blob/7099c6ec7345e46a4baa101342ae9e5a31556aaf/st.c#L2216-L2221

If you remove those then I believe that it should no longer clear the scrollback history.

\
Thanks,

-Stein

**Comment by UtkarshVerma** [comment]
Thanks for the response. I commented out clearing of the history in the CSI hander but the history is still being cleared on `Ctrl + l`.

**Comment by bakkeby** [comment]
That is odd, I couldn't replicate the scrollback history being cleared after commenting that out.

**Comment by UtkarshVerma** [comment]
It is reproducible on `main` branch of this repo. These are the patches I enabled without changing any config.
```c
#define ALPHA_PATCH 1
#define ANYSIZE_SIMPLE_PATCH 1
#define BLINKING_CURSOR_PATCH 1
#define BOXDRAW_PATCH 1
#define COLUMNS_PATCH 1
#define COPYURL_HIGHLIGHT_SELECTED_URLS_PATCH 1
#define CSI_22_23_PATCH 1
#define DELKEY_PATCH 1
#define LIGATURES_PATCH 1
#define OPENCOPIED_PATCH 1
#define OSC_10_11_12_2_PATCH 1
#define SCROLLBACK_PATCH 1
#define SCROLLBACK_MOUSE_ALTSCREEN_PATCH 1
#define SYNC_PATCH 1
#define UNDERCURL_PATCH 1
#define WIDE_GLYPHS_PATCH 1
#define WORKINGDIR_PATCH 1
```

**Comment by JimPix1** [comment]
I commented out
```
term.scr = 0;
 term.histi = 0; 
 for (int i = 0; i < HISTSIZE; i++) 
 	term.hist[i][0].u = '\0'; 
```
 And it also doesn't work for me

**Comment by bakkeby** [comment]
It looks like the main issue here is how the screen is cleared.

Adding some `fprintf` statements for me when doing `Ctrl+l` it first goes through `case 2: /* screen */` then it goes through `case 0: /* below */`.

In this case the scrollback buffer is preserved, but anything that was on the screen when the clear happened will be gone as the clearing just blanks out everything on the screen and starts drawing from row 0. Maybe it is possible to more accurately preserve the scrollback buffer if one were to artificially scroll down before the clearing happens, but I am not entirely sure how to accomplish that.
