### ISSUE TITLE
Mouse Scrollback does not work in manpages with the correct patches enabled

### ISSUE THREAD

**Issue by JimPix1** [bakkeby/st-flexipatch#52]
I cannot mouse scroll in manpages with st-flexipatch
I have enabled the scrollback, scrollback-mouse and scrollback-mouse-altscreen patches. Scrolling with the mouse works in the terminal but not in manpages specifically.
Interestingly manpage mouse scrolling works in Distrotube's build https://gitlab.com/dwt1/st-distrotube
I tried replacing the kscrollup and kscrolldown bindings in config.h with the bindings that DT used
``   { XK_ANY_MOD,           Button4, kscrollup,      {.i = 3},      0, /* !alt */ -1 },``
``      { XK_ANY_MOD,           Button5, kscrolldown,    {.i = 3},      0, /* !alt */ -1 },``
      
However when I do this I get the following warning:
      
```
[matt@mpc ~/st-flexipatch]$ sudo make install 
c99 -I/usr/X11R6/include  `pkg-config --cflags fontconfig`  `pkg-config --cflags freetype2`  `pkg-config --cflags harfbuzz` -DVERSION=\"0.8.4\" -D_XOPEN_SOURCE=600  -O1 -c st.c 
c99 -I/usr/X11R6/include  `pkg-config --cflags fontconfig`  `pkg-config --cflags freetype2`  `pkg-config --cflags harfbuzz` -DVERSION=\"0.8.4\" -D_XOPEN_SOURCE=600  -O1 -c x.c 
In file included from x.c:59: 
config.h:192:87: warning: excess elements in struct initializer 
  192 |         { XK_ANY_MOD,           Button4, kscrollup,      {.i = 3},      0, /* !alt */ -1 }, 
      |                                                                                       ^ 
config.h:192:87: note: (near initialization for ‘mshortcuts[0]’) 
config.h:193:87: warning: excess elements in struct initializer 
  193 |         { XK_ANY_MOD,           Button5, kscrolldown,    {.i = 3},      0, /* !alt */ -1 }, 
      |                                                                                       ^ 
config.h:193:87: note: (near initialization for ‘mshortcuts[1]’) 
c99 -I/usr/X11R6/include  `pkg-config --cflags fontconfig`  `pkg-config --cflags freetype2`  `pkg-config --cflags harfbuzz` -DVERSION=\"0.8.4\" -D_XOPEN_SOURCE=600  -O1 -c hb.c 
c99 -o st st.o x.o hb.o -L/usr/X11R6/lib -lm -lrt -lX11 -lutil -lXft -lXrender  `pkg-config --libs fontconfig`  `pkg-config --libs freetype2`  `pkg-config --libs harfbuzz` 
mkdir -p /usr/local/bin 
cp -f st /usr/local/bin 
chmod 755 /usr/local/bin/st 
mkdir -p /usr/local/share/man/man1 
sed "s/VERSION/0.8.4/g" < st.1 > /usr/local/share/man/man1/st.1 
chmod 644 /usr/local/share/man/man1/st.1 
tic -sx st.info 
7 entries written to /usr/share/terminfo 
mkdir -p /usr/local/share/applications # desktop-entry patch 
cp -n st.desktop /usr/local/share/applications # desktop-entry patch 
Please see the README file regarding the terminfo entry of st. 
```

In addition, those keybinds are the same keybinds that are used in the scrollback-altscreen patch on the suckless site so I'm not sure why I'm thrown such a warning.

How could this be fixed?

**Comment by bakkeby** [comment]
I am not entirely sure as I was not able to replicate the issue of scrolling in man pages in st. Scrolling in man pages seem to work just fine in an unpatched st.

As for the warning you are receiving here this is because the alt option comes from the [universcroll](https://st.suckless.org/patches/universcroll/) patch.

```c
config.h:193:87: warning: excess elements in struct initializer 
  193 |         { XK_ANY_MOD,           Button5, kscrolldown,    {.i = 3},      0, /* !alt */ -1 }, 
```

> In addition, those keybinds are the same keybinds that are used in the scrollback-altscreen patch on the suckless site

I see that the [st-scrollback-mouse-altscreen-20190131-e23acb9.diff](https://st.suckless.org/patches/scrollback/st-scrollback-mouse-altscreen-20190131-e23acb9.diff) patch differs from [st-scrollback-mouse-altscreen-20200416-5703aa0.diff](https://st.suckless.org/patches/scrollback/st-scrollback-mouse-altscreen-20200416-5703aa0.diff), the latter of which seems to be more or less the same as the universcroll patch.

Can you see if enabling `UNIVERSCROLL_PATCH` and disabling both `SCROLLBACK_MOUSE_PATCH` and `SCROLLBACK_MOUSE_ALTSCREEN_PATCH` works better for you?

**Comment by JimPix1** [comment]
> Can you see if enabling `UNIVERSCROLL_PATCH` and disabling both `SCROLLBACK_MOUSE_PATCH` and `SCROLLBACK_MOUSE_ALTSCREEN_PATCH` works better for you?
Scrolling in manpages now works however I can't scroll in st now, Everytime I try I'm just met with a repeat of 2~2
![image](https://user-images.githubusercontent.com/79943327/153458482-d0dba603-dff9-4bd8-ac36-264718c00a7c.png)
