### ISSUE TITLE
Xresources doesn't work if custom window instance is set

### ISSUE THREAD

**Issue by rteats** [bakkeby/st-flexipatch#53]
Literally the title. If you try to launch `st` with a different process name besides `$TERM` (in my case, dwm-flexipatch's [scratchpads patch](https://github.com/bakkeby/dwm-flexipatch/blob/master/patch/scratchpad.c) seems to do so) while having in your `.Xresources`, for example, some sexy colorscheme, then that colorscheme won't get applied. Is there any fix for that?

**Comment by bakkeby** [comment]
What other process name would you have?

**Comment by rteats** [comment]
Sorry for late reply. I actually meant to say window instance name instead of process name. The patch spawns st with a `spterm` window instance name. I hope it's more informative now.

**Comment by bakkeby** [comment]
I'm not sure. If you st via dmenu does the settings from your .Xresources apply?

All in all it sounds a bit strange. Do you use .Xresources for dwm as well?

None of the xresources patches for dwm, st and dmenu actually read from your ~/.Xresources file, but from the X session. If you have loaded resources (e.g. xrdb ~/.Xresources) then you should see a RESOURCES property on the root window with all the settings. To check this you can open as floating terminal, run `xprop` and click on the desktop background.

**Comment by rteats** [comment]
Yes, launching st via dmenu does apply the settings from .Xresources. Yes, I do use .Xresources for dwm as well. `xprop` does show all the settings that are present in the resources file. The scratchpad window instance doesn't apply the settings. Also, launching st with `-n foobar` flag doesn't apply the settings.

**Comment by bakkeby** [comment]
That is interesting. 

https://github.com/bakkeby/st-flexipatch/blob/7099c6ec7345e46a4baa101342ae9e5a31556aaf/patch/xresources.c#L13-L16

It looks for different resources depending on the title and class. 

So if the class is the same then you can use "St." as the prefix, alternatively it might work if you define "*." as the prefix in your .Xresources file. 

Wasn't aware that the patch for st worked this way.

**Comment by rteats** [comment]
Changing `st.` to `*.` does fix the problem! Thanks! But I think that other people should be aware of this too. Should I close this issue now?

**Comment by bakkeby** [comment]
It is not listed on the [suckless](https://st.suckless.org/patches/xresources/) patch page, but the feature looks intentional. I suppose that it is in line with the [Xresources](https://wiki.archlinux.org/title/x_resources) syntax where it reads different resources depending on the name or class, as such you can theme your scratchpads separately should you want to which is kind of neat.
