### ISSUE TITLE
st-flexipatch gives errors when using nvim

### ISSUE THREAD

**Issue by JimPix1** [bakkeby/st-flexipatch#54]
When I use neovim in st I get these errors:
```
erresc: unknown csi ESC[22;0;0t

erresc: unknown csi ESC[22;0t

erresc: invalid color j=258, p=?

erresc: unknown csi ESC[23;0;0t

erresc: unknown csi ESC[23;0t
```

This only happens when I use nvim and I have seen other people with this error but I haven't found a fix for it. I do know that distrotube's build doesn't have this issue however I don't want to switch to his build. These errors annoyingly clog up the ~/.xsession-errors file

**Comment by JimPix1** [comment]
UPDATE:
```c
		case 4: /* color set */
			if (narg < 3)
				break;
			p = strescseq.args[2];
			/* FALLTHROUGH */
		case 104: /* color reset, here p = NULL */
			j = (narg > 1) ? atoi(strescseq.args[1]) : -1;
			if (xsetcolorname(j, p)) {
				if (par == 104 && narg <= 1)
					return; /* color reset without parameter */
				fprintf(stderr, "erresc: invalid color j=%d, p=%s\n",
				        j, p ? p : "(null)");
			} else {
				/*
				 * TODO if defaultbg color is changed, borders
				 * are dirty
				 */
				redraw();
			}
			return;
		}
		break;
```
changing the colour set section to this solved it

**Comment by bakkeby** [comment]
As for the invalid color error

> erresc: invalid color j=258, p=?

It looks like this has been fixed in the upstream st ref. https://git.suckless.org/st/file/st.c.html#l1932

That is applying something slightly different to the [OSC 10, 11, 12 #2](https://st.suckless.org/patches/osc_10_11_12_2/) patch. I shall have a closer look at this tomorrow.

**Comment by JimPix1** [comment]
Thanks for the replies!
I'll have to make a new st-flexipatch to apply the ``CSI_22_23_PATCH`` so I'll wait until you find a solution for the invalid colour error before doing so :+1:

**Comment by bakkeby** [comment]
I just pushed changes upgrading to latest master of st (v0.8.5, e823e23, 2022-02-17). The invalid color error is no longer appearing if I start nvim.

**Comment by JimPix1** [comment]
Great! So if I just make a new st-flexipatch and apply the ``CSI_22_23_PATCH`` I won't get any errors with nvim anymore?

**Comment by JimPix1** [comment]
This has indeed solved it
