### ISSUE TITLE
ligatures error 

### ISSUE THREAD

**Issue by xaotag** [bakkeby/st-flexipatch#60]
![image](https://user-images.githubusercontent.com/40427877/159101117-4ac80543-2e70-4914-8c43-619027bb3c8b.png)
![image](https://user-images.githubusercontent.com/40427877/159101133-35fc2f05-e84e-4798-9899-d493f9f6ae2b.png)

**Comment by xaotag** [comment]
@bakkeby

**Comment by bakkeby** [comment]
Have a look in discussion #25.
