### ISSUE TITLE
Unknown CSI errors in st-flexipatch when opening and closing neovim

### ISSUE THREAD

**Issue by JimPix1** [bakkeby/st-flexipatch#63]
I had this problem before and applying a newer CSI patch fixed it, however these errors seem to have returned whenever I do ``st -e nvim``
```
erresc: unknown csi ESC[>4;2m
erresc: unknown csi ESC[>4;0m
```
Opening nvim in st normally is fine, it's when I do ``st -e nvim`` that gives trouble, even doing something like ``st -e sleep 2; nvim`` doesn't output an error, so it's something specific. It may be to do with neovim 7.0 having been released?

**Comment by bakkeby** [comment]
Quite possibly nvim is using some new escape codes. You can always just comment out the two lines that write those warnings if you find them annoying.
 
Do you use the sixel patch by any chance?

**Comment by JimPix1** [comment]
No, I don't. How would I comment out those two lines?

**Comment by JimPix1** [comment]
Found the two lines and commented them out, thanks bakkeby!
![image](https://user-images.githubusercontent.com/79943327/164755180-8dbf2725-aeb9-4367-aed6-ca0a71d6087c.png)
