### ISSUE TITLE
st -e lf breaks ueberzug previews?

### ISSUE THREAD

**Issue by der-zonk** [bakkeby/st-flexipatch#64]
This is weird.. I got previews in lf** running with lfimg*** using ueberzug no problem in st-flexipatch when starting lf withing st.
But when I use `st -e lf` in a shortcut the image preview is broken on images and videos..

patches applied:
ALPHA_PATCH 1
COLUMNS_PATCH 1
HIDE_TERMINAL_CURSOR_PATCH 1
KEYBOARDSELECT_PATCH 1
SYNC_PATCH 1
UNIVERSCROLL_PATCH 1
WIDE_GLYPHS_PATCH 1
XRESOURCES_PATCH 1
XRESOURCES_RELOAD_PATCH 1

** https://github.com/gokcehan/lf
*** https://github.com/cirala/lfimg

I don't even know if this is an st issue..

**Comment by bakkeby** [comment]
Probably worth disabling one patch at a time to see if it is one of the patches causing it. My best guess would be that it has something to do with the alpha patch / transparency.

**Comment by der-zonk** [comment]
I removed all patches and it's still the same..

Oh my god my bad.. You have to run lf with the wrapper script lfrun for the images to work which I only aliased in the .bashrc that's why it didn't work with a shortcut.. sorry -.-
