### ISSUE TITLE
Can't take screenshots of st using maim in certain instances

### ISSUE THREAD

**Issue by JimPix1** [bakkeby/st-flexipatch#69]
I have had this problem for months and it has *killed* me inside.
 Essentially, when I use maim to take a screen and xclip to copy it to the clipboard, most of the time it doesn't work and when I try to paste it in Firefox it freezes for several seconds. I have been totally unable to solve this and I can screenshot every other thing, except my terminal.
 I've had to use Flameshot for a lot of stuff now which I hate for multiple reasons and even then, sometimes it doesn't work properly. Today I made a fresh st-flexipatch and the problem still, annoyingly, persists.
 Has anybody got any clue how to fix this? I might have to finally say goodbye to st and try something like alacritty to see if the problem is solved on another terminal.

**Comment by bakkeby** [comment]
Could you show the exact command you use to take the screenshot and copying it to the clipboard?

Also are you using a clipboard manager? If so which one.

**Comment by JimPix1** [comment]
The command I generally use is 
 maim -u | xclip -selection clipboard -t image/png
 The only clipboard manager I use is clipmenu, which uses dmenu and has no image support

**Comment by JimPix1** [comment]
Thank you very much for this, I *may* :pray: have fixed this.
I simply added the --format jpg to the maim command however I kept xclip as image/png instead of image/jpeg (Did quick testing and using image/jpeg wouldn't work when I tried to paste stuff in discord, did work with Gnome Drawing though). So far it seems to work fine, I'll keep this issue open for today and maybe tomorrow as it's entirely possible it'll stop working again.

**Comment by JimPix1** [comment]
Ok so it does work, yes, but I have an issue.
I was using Element (matrix client) and I pasted one of my screenshots in it and it wouldn't work properly (didn't actually show the image, you had to download it). doing --format jpg and xclip -t image/jpeg doesn't work, and using --format png and xclip -t image/png causes the freezing. is there any one solution here?

**Comment by bakkeby** [comment]
xclip doesn't perform any image conversion though - I think that `-t` argument just sets a hint indicating what the clipboard data is. So if you make maim produce a JPG image and you advertise that as a PNG image, then that can surely lead to confusion on the application side as it receives data that does not look like PNG format. Some programs will be able to detect this and disregard the hint provided, but others may give an error (or freeze for that matter).

**Comment by JimPix1** [comment]
But when I make xclip use the jpeg format Firefox nothing gets pasted into Firefox, so it's very odd

**Comment by JimPix1** [comment]
> Does it make any difference if you use bmp or webp formats? The latter will likely not be supported everywhere.

the bmp format causes freezing and webp only works when xclip is set to image/png, just like the jpg format. Setting xclip to webp pastes nothing into Firefox. So webp has the problem as jpg and bmp just doesn't work

**Comment by JimPix1** [comment]
Hm, any more ideas on this? This really is odd, on my old laptop I never had this issue, or even on this laptop when it ran Linux Mint. However since I installed Arch on this laptop I've had the problem.
Do you think it's related to maim or xclip?

**Comment by JimPix1** [comment]
Hm, this doesn't seem exclusive to screenshotting st, I notice the bug to be much more prevalent when a window is small in dwm's floating mode, st, firefox etc.

**Comment by bakkeby** [comment]
> I notice the bug to be much more prevalent when a window is small in dwm's floating mode, st, firefox etc.

That seems aligned with the idea that the larger the image the slower it becomes.

We have already ascertained that you are not using a clipboard manager which is fine, I don't use one either.

When you run your command xclip will continue running in the background waiting for you to paste the image. When you copy something else then xclip will exit as the clipboard data has changed. 

If you run xclip with the `-verbose` option then xclip will remain in your terminal until you copy something else (or stop it).

```sh
$ maim -s | xclip -verbose -selection clipboard -t image/png
Connected to X server.
Using selection: XA_CLIPBOARD
Using image/png.
Waiting for selection requests, Control-C to quit
  Waiting for selection request number 1
  Waiting for selection request number 2
  Waiting for selection request number 3
```

So when you paste you should see that it starts waiting for the next selection request. If I paste into gimp for example then it moves on to waiting for the next request relatively quickly, followed by a small delay before the image appears in the image application. This suggests that xclip returns the data quickly and the rest of the delay happens on the application side processing / decoding the data.

Does the verbose output give any clues as to what is causing the slowdown on your end?

I would stick to png for both maim and xclip when testing this, or at least use the right mime type representing the image format of the data in the clipboard.

**Comment by JimPix1** [comment]
Using the verbose option I found that when it freezes, nothing happens in xclip's output
![image](https://user-images.githubusercontent.com/79943327/174277591-ceb5c18a-c111-4a5c-a89d-c6cd573914a6.png)
I should also mention as I think it's important, When I paste a screenshot taken with maim and Firefox would freeze, if I saved the image to my laptop rather than piping it into xclip, it does not freeze when I send it etc.
So I have a feeling this is to do with either xclip or my browser

**Comment by JimPix1** [comment]
Aha! Aha! Aha!
I have just discovered something very interesting indeed.
So, I screenshotted a small terminal to try and replicate the freezing and Firefox froze. then I ran this command in that terminal
``maim -u --format=png | xclip -selection clipboard -t image/png``
Firefox did still freeze when pasting it so I then ran this
``xclip -o -selection clipboard | file -``
And, very weirdly I got this output
``[matt@mpc ~]$ xclip -o -selection clipboard | file - ``
``/dev/stdin: ASCII text, with no line terminators``
![image](https://user-images.githubusercontent.com/79943327/174287351-821152b8-14fb-4816-916c-b5720c093593.png)

So I repeated these steps in a fresh, large terminal that I confirmed didn't freeze firefox and would you believe it
![image](https://user-images.githubusercontent.com/79943327/174287419-8f7fa2a2-f9bd-436d-985e-712f31bddaf5.png)
No problem at all..
So this seems to me like an xclip issue.

**Comment by JimPix1** [comment]
Now when I try this again with a screenshot that freezes firefox, xclip simply can't process it and hangs
![image](https://user-images.githubusercontent.com/79943327/174290142-142d58f9-15f9-437c-841a-9be3b4801d3f.png)

**Comment by JimPix1** [comment]
Holy shit I fixed it lol
It was xclip's fault entirely.
I literally just installed xclip-git from the AUR and it's solved.
I checked it out, and the xclip package in the repos has not been updated in over 2 years. 
![image](https://user-images.githubusercontent.com/79943327/174291956-4e2e41ec-3019-4b99-a82c-d9223e54a733.png)
Currently the xclip package is 61 commits behind and obviously one of them fixed the issue. The xclip package should seriously be updated..

**Comment by JimPix1** [comment]
I spoke with an Arch Linux repository maintainer and they said that they're not able to update it because they have to use every stable release. xclip 0.13-3 is the latest stable xclip version and is also the one in the Arch Linux repos, which, really coincidentally and entirely not the reason I had my issue - xclip 0.13 was released in *2016*
So the xclip package is way behind xclip on github because the xclip devs won't make a new stable release..

**Comment by bakkeby** [comment]
Great debugging. Yes I see I also have 0.13-3 on my system.

```sh
$ paru -F xclip
extra/xclip 0.13-3 [installed]
    usr/bin/xclip
```

Glad you got your problem sorted out.

**Comment by JimPix1** [comment]
Thanks for your help! And sorry for wasting your time, in the beginning I believed it was actually an st problem haha
