### ISSUE TITLE
rightclickpaste

### ISSUE THREAD

**Issue by MrRawes** [bakkeby/st-flexipatch#70]
could the [rightclickpaste](https://st.suckless.org/patches/rightclickpaste/) patch be added

**Comment by avih** [comment]
> could the [rightclickpaste](https://st.suckless.org/patches/rightclickpaste/) patch be added

It's not needed anymore because it's now configurable via `config.h`.

Just change this to `Button3` https://github.com/bakkeby/st-flexipatch/blob/master/config.def.h#L348
