### ISSUE TITLE
fatal error: arch/limits.h: No such file or directory

### ISSUE THREAD

**Issue by tienbuigia** [bakkeby/st-flexipatch#71]
I'm trying to compile but got a weird error.

This is output of `make`

> st build options:
CFLAGS  = -I/usr/X11R6/include  -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread   -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread   -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -DVERSION="0.8.5" -D_XOPEN_SOURCE=600  -O1
LDFLAGS = -L/usr/X11R6/lib -lm -lrt -lX11 -lutil -lXft -lXrender  -lfontconfig -lfreetype   -lfreetype   -lharfbuzz
CC      = c99
c99 -I/usr/X11R6/include  `pkg-config --cflags fontconfig`  `pkg-config --cflags freetype2`  `pkg-config --cflags harfbuzz` -DVERSION=\"0.8.5\" -D_XOPEN_SOURCE=600  -O1 -c st.c
In file included from st.c:5:
/usr/local/include/limits.h:4:10: fatal error: arch/limits.h: No such file or directory
    4 | #include <arch/limits.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:25: st.o] Error 1
[ble: exit 2]

**Comment by tienbuigia** [comment]
I just realize that it's my machine problem, it can't even compile with `stdio.h`.

**Comment by bakkeby** [comment]
Not sure about this exact error, perhaps check if you have the `base-devel` package installed.
