### ISSUE TITLE
barmodules center alignment isn't accurate & others

### ISSUE THREAD

**Issue by wael444** [bakkeby/st-flexipatch#72]
![image](https://user-images.githubusercontent.com/47404953/175539072-3b9c5f99-eaaf-40b0-ab3f-83484e77ff54.png)
status is set to a long `foo` for example.

one of the only patches i know that can center is [centretitle]( https://dwm.suckless.org/patches/centretitle/dwm-centretitle-20200907-61bb8b2.diff)

2 other issues i have is that when the configuration has all the bars on only monitor 0, when a window is created on monitor 1, dwm crashes:
```c
static const BarRule barrules[] = {
	/* monitor  bar    alignment         widthfunc              drawfunc              clickfunc           name */
	{ 0,      0,     BAR_ALIGN_RIGHT,  width_systray,         draw_systray,         click_systray,      "systray" },
	{ 0,      0,     BAR_ALIGN_RIGHT,  width_status,          draw_status,          click_status,       "status" },
	{ 0,      0,     BAR_ALIGN_CENTER,   width_tags,            draw_tags,            click_tags,         "tags" },
	{ 0,      0,     BAR_ALIGN_LEFT,   width_ltsymbol,        draw_ltsymbol,        click_ltsymbol,     "layout" },
	{ 0,      0,     BAR_ALIGN_NONE,   width_wintitle,        draw_wintitle,        click_wintitle,     "wintitle" },
};
```

also some weird unnessesary padding on systray:
![image](https://user-images.githubusercontent.com/47404953/175540272-d4be3509-184b-4efc-86a4-7d8f331aa10d.png)

**Comment by bakkeby** [comment]
According to your bar rules the systray is to be drawn first, then it is to draw the status, and after that the tag icons are to be centered in the remaining space. 

If you want the tag icons to be centered on the bar then have this as the first rule, then add systray to the right of the right hand side, etc.

**Comment by wael444** [comment]
> According to your bar rules the systray is to be drawn first, then it is to draw the status, and after that the tag icons are to be centered in the remaining space.

that was intentional to prevent
![image](https://user-images.githubusercontent.com/47404953/175617040-e60f3e97-ff68-4d5b-9711-89f96dc123ec.png)

**Comment by bakkeby** [comment]
Not following.

**Comment by wael444** [comment]
*ahem*

Currently, i am facing a problem where the `BAR_ALIGN_CENTER` on `tags` does not actually center.

it's position is moved to the right according to `width_systray` and `width_status`. [1]

you had said previously that the position of `tags` is due to having the `status` and `systray` ontop of the `tags` in the `barrules[]` - i had later then changed their positions to be placed under `tags` and that ended up having both of them on the left side of `tags`. [2]

+ 1:
![image](https://user-images.githubusercontent.com/47404953/175642312-b21277c5-410c-4251-a806-70c22a693153.png)
+ 2:
![image](https://user-images.githubusercontent.com/47404953/175642786-589cbab7-f3a6-4b60-a223-1910fa8e3ab4.png)

**Comment by bakkeby** [comment]
Ok. So you have the width of the bar right. You then say that the tags are to be placed in the dead center of the bar. 

Now you end up with two regions of the bar; the remaining space on the left hand side of the bar and the remaining space on the right hand side of the bar. 

At this point you will want to specify whether the alignment position is on the left or right hand side of the bar. 

So if you set the status to be BAR_ALIGN_RIGHT_RIGHT then that will place the status on the far right of the right hand side of the bar. 

When you set the systray to be BAR_ALIGN_CENTER_RIGHT then you said to place the systray in the center of the right hand side of the bar. 

In the above example the BAR_ALIGN_RIGHT will place the module on the right hand side of the available space that comes first, which is the left hand side of the bar.

There are some notes on these here:
https://github.com/bakkeby/patches/wiki/barmodules

**Comment by wael444** [comment]
doing
```c
static const BarRule barrules[] = {
	/* monitor  bar    alignment         widthfunc              drawfunc              clickfunc           name */
	{ -1,      0,     BAR_ALIGN_RIGHT_RIGHT,  width_status,          draw_status,          click_status,       "status" },
	{ -1,      0,     BAR_ALIGN_CENTER, width_tags,            draw_tags,            click_tags,         "tags" },
};
```
gives me the same result as what my issue is for but when i do
```c
static const BarRule barrules[] = {
	/* monitor  bar    alignment         widthfunc              drawfunc              clickfunc           name */
	{ -1,      0,     BAR_ALIGN_CENTER, width_tags,            draw_tags,            click_tags,         "tags" },
	{ -1,      0,     BAR_ALIGN_RIGHT_RIGHT,  width_status,          draw_status,          click_status,       "status" },
};
```
it seems my problem is solved, but i will not be closing this only after i manage to get all the modules in their places. thanks.

**Comment by wael444** [comment]
this is the st-flexipatch repository, sorry for opening this issue in the wrong repository.
