### ISSUE TITLE
Feat req: Add glyphs to boxdraw patch

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/st-flexipatch#79]
Would it be possible to add the glyphs "▏" and "▎" to the boxdraw patch? I use them for git signs and indentlines in my nvim config and having these drawn as long lines would be awesome.

By the way, Alacritty and foot seem to include this glyph by default, so maybe their source code could be helpful here.

Here's a comparison:
![image](https://user-images.githubusercontent.com/31820255/186352185-90757255-38eb-4473-8ab1-e7eebfe63801.png)

Left is Alacritty and st on the right.

You can see that the glyphs are not being joined in the case of st.

**Comment by bakkeby** [comment]
Some analysis.

`▎` - code point U258E LEFT ONE QUARTER BLOCK
`▏` - code point U258F LEFT ONE EIGHT BLOCK

According to https://st.suckless.org/patches/boxdraw/ we have that:

> Supported codepoints are U2500 - U259F except dashes and diagonals, and U28XX.

If I try to echo these characters they turn out as continuous lines.

![image](https://user-images.githubusercontent.com/1438008/186357232-4b97bf6d-fdb9-4ecf-b78c-c8c6c4251fa2.png)

There also does not appear to be a different between normal and alt screen.

Increasing `chscale` in config.h does not affect this.
Increasing `chscale` in combination with the vertcenter patch does not affect this.

The font used can and will have an effect, but in this case it looks like the same font is used in both st and Alacritty.

Using a font that does not have these glyphs and using different fallback fonts via the font2 patch does not appear to make a difference 

The wide glyphs patch did not appear to have an impact on this.

So far I have not been able to reproduce this issue.

If you show what patches you have enabled and your config.h then I can try with that.

**Comment by UtkarshVerma** [comment]
Thanks for the quick reply. You can find my build here: 
https://github.com/UtkarshVerma/dwm

In the screenshot I attached, both are using the same font. But I suspect font resolution could also be related over here because I use a custom font family defined through fontconfig.

The fontconfig is here:
https://github.com/UtkarshVerma/dotfiles/blob/main/.config/fontconfig/fonts.conf

Both terminals use the monospace font.

**Comment by avih** [comment]
> Here's a comparison: ![image](https://user-images.githubusercontent.com/31820255/186352185-90757255-38eb-4473-8ab1-e7eebfe63801.png)
> 
> Left is Alacritty and st on the right.
> 
> You can see that the glyphs are not being joined in the case of st.

You probably don't have boxdraw enabled.

Even if you enable the patch, the boxdraw rendering is disabled by default and controlled from `configh.h`, so you need to edit it and enable boxdraw.

**Comment by UtkarshVerma** [comment]
Yeah, you're right. Enabling it now renders them properly. However, now rounded boxes are not rendered properly, e.g. telescope in nvim.

![image](https://user-images.githubusercontent.com/31820255/186375405-893f92d9-25fa-40e7-8e6f-486f5283b755.png)

**Comment by avih** [comment]
> rounded boxes are not rendered properly

That's how boxdraw does rounded corners.

**Comment by UtkarshVerma** [comment]
> > rounded boxes are not rendered properly
> 
> That's how boxdraw does rounded corners.

Is there some way I can modify st to allow for rounded corners?

**Comment by avih** [comment]
> > > rounded boxes are not rendered properly
> > 
> > 
> > That's how boxdraw does rounded corners.
> 
> Is there some way I can modify st to allow for rounded corners?

The boxdraw patch does not support rendering rounded corners as actual arcs. So if you must have your rounded corners perfectly rounded, then it won't be boxdraw which renders them.

So to render rounded corners from the font, you have two options:
1. Disable boxdraw completely and live with the possible misalignment which boxdraw solves.
2. Disable only the boxdraw rendering of rounded-corners codepoints. This option is not configurable, so you'd need to delete these lines from your copy of `boxdraw.h`: https://github.com/bakkeby/st-flexipatch/blob/master/patch/boxdraw.h#L179-L183 and then the rounded corners might or might not align correctly with other lines which boxdraw renders.

**Comment by bakkeby** [comment]
This text file is useful for testing this kind of thing.
https://gist.githubusercontent.com/msabramo/3921955/raw/197676521564c05d03aa59ec0ce52d23a3fc2a7e/UTF-8-demo.txt

Default boxdraw:
![image](https://user-images.githubusercontent.com/1438008/186426997-fef90117-8fe6-4a4f-892b-9e42086bad75.png)

With those lines commented out:
![image](https://user-images.githubusercontent.com/1438008/186426784-5991f2a6-176d-47be-9563-2e422351ea6d.png)

**Comment by avih** [comment]
> With those lines commented out:
> ![image](https://user-images.githubusercontent.com/1438008/186426784-5991f2a6-176d-47be-9563-2e422351ea6d.png)

In your case the rounded corners align nearly perfectly, but it highly depends on the font, size, and st configuration values.

The same is true also for any other codepoints which you want to be rendered from the font instead of by the boxdraw patch.

In general, if alignment with your font is fine without boxdraw, then you don't need boxdraw...

**Comment by UtkarshVerma** [comment]
It works fine with other terminals so I guess this is something related to my font settings in st. This how the file renders for me without boxdraw:

![image](https://user-images.githubusercontent.com/31820255/187272272-f85909bb-f44a-4d0b-95ab-a39f91c131c0.png)

I'll try to get this to work without using the boxdraw patch. Do you have any suggestions where I could look?

**Comment by UtkarshVerma** [comment]
I could change the chscale to 0.96 and the lines seem to join up. Is this a hacky workaround?

**Comment by UtkarshVerma** [comment]
It's a font issue after all. Opened up VS Code and found the same behaviour. I guess Alacritty and foot are doing some guesswork based on the glyph, but it doesn't make sense to bring it to st. I've opened up an issue in JetBrains repo for now.

https://github.com/JetBrains/JetBrainsMono/issues/554

@avih @bakkeby your fonts look nice. Could you please let me know which font you guys are using?

**Comment by avih** [comment]
> Is this a hacky workaround?

You shouldn't care what other people think, unless you intend to send a PR to merge your change - which you don't.

If it's good enough for you then just use it.

> your fonts look nice. 

I only quoted the image from the message above. I didn't post an image with my fonts.

**Comment by bakkeby** [comment]
@UtkarshVerma I use the [Comic Code](https://tosche.net/fonts/comic-code) font. It is a paid font but I haven't regretted investing in it.

**Comment by UtkarshVerma** [comment]
Thanks

**Comment by UtkarshVerma** [comment]
@bakkeby The font looks really good. I tried the free demo and noticed that it looks a bit too congested. Could you please send me your st config.h and patches.h file so that I could configure it accordingly.

![image](https://user-images.githubusercontent.com/31820255/187309542-79b11726-375c-4b37-91f8-5a5050791d1e.png)

Glyphs not leaving vertical padding for the statusbar:
![image](https://user-images.githubusercontent.com/31820255/187309595-e37e050d-513b-46db-8a97-793be90fee99.png)

This is how I want it to be (this is JetBrainsMono):
![image](https://user-images.githubusercontent.com/31820255/187309807-a9f1f57a-a521-477c-a86a-9b0e589d0247.png)

**Comment by bakkeby** [comment]
If you are using the Comic Mono font then that is an entirely different font based on the same idea (was the author's first attempt if I recall correctly). It does not look nearly as good. 

If you go to the buy options on the two stores then there should be a demo download that cost 0,00 - this has all alphanumeric characters, but it is missing basic characters (like a punctuation mark for example) which in my opinion makes it hard to evaluate.

**Comment by UtkarshVerma** [comment]
> If you are using the Comic Mono font then that is an entirely different font based on the same idea (was the author's first attempt if I recall correctly). It does not look nearly as good.
> 
> If you go to the buy options on the two stores then there should be a demo download that cost 0,00 - this has all alphanumeric characters, but it is missing basic characters (like a punctuation mark for example) which in my opinion makes it hard to evaluate.

Yeah, but I tried the demo font, and it looks congested in the vertical direction in general. If you look at the statusline images, you can see very left space if left in Comic Code font (above and below the font) as compared to JetBrains Mono.

Do you modify chscale in your build? How are you handling this behaviour?

**Comment by bakkeby** [comment]
I see now, yes the font is congested in the vertical direction like that. I suppose that is a good thing as it allows for text to be condensed if need be.

I added top and bottom padding for my editor, but for the terminal it didn't bother me.

In st I suppose I'd use chscale of 1.2 combined with the vertcenter patch.
