### ISSUE TITLE
Entering a Directory with a .git directory in it, make st crash

### ISSUE THREAD

**Issue by MrMic** [bakkeby/st-flexipatch#8]
Hi,

I got many Directories that have .git directory inside, and when I try to "cd" 
inside such directory with st, it crashes!
This issue is also in the stock st app (I have tryed 0.8.4 version).

Have you noticed that, you too?
Otherwise, all I have tryed so far, works very well.

Rgds,

**Comment by bakkeby** [comment]
Can't say that I have ever heard about this issue before.

I am assuming that you have something that changes the prompt when you are in a git directory - if so what do you use and how does it look (in other terminals)?

**Comment by MrMic** [comment]
Yes, indeed !
I have Starship (a prompt written in Rust), and after deactivate it, all 
work as expected.
Starship was working perfectly fine with all the other terminals I use; :((
Disappointing.

Thank anyway for the quick reply.

Rgds,

**Comment by bakkeby** [comment]
Without having it activated, can you replicate the crash by running
```bash
starship prompt
```
?

I tried with the latest st 8.4 from git and it seemed fine.

It might be something in your starship.toml configuration file, I can have a look if you'd like to share that.

**Comment by avih** [comment]
> It might be something in your starship.toml configuration file

Could also be font-related. Startship seems to use some Unicode icons (at least for git dirs), and if one of those is in color at the font used (like color emoji), then it might need the patched xft (libxft-bgra) - and is an issue of xft - outside the control of st.

**Comment by MrMic** [comment]
Here is my starship.toml:
```
# Disable the newline at the start of the prompt
add_newline = false

# Overwrite a default_prompt_order and  use custom prompt_order
# prompt_order=["conda","character"]

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

format = "$all"

[character]
# symbol = "➜"
error_symbol = "✗"
use_symbol_for_status = true

[conda]
symbol = "🅒 "
style = "bold green"
ignore_base = false
format = "${symbol}${environment} ($style)"
disabled = false

[python]
symbol = "🐍 "
style = "yellow bold"
pyenv_version_name = true
format = "via [${symbol}${pyenv_prefix}${version}( ($virtualenv))]($style) "

[username]
show_always = true

[hostname]
ssh_only = false
format = "⟪ $hostname ⟫ "
trim_at = "-localdomain-local"
disabled = false

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "👅"
deleted = "🗑"

[git_branch]
symbol = "🌱 "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 4

[git_state]
progress_divider = " of "
cherry_pick = "🍒 PICKING"

[java]
symbol = "🌟 "

[nodejs]
symbol = "🤖 "
style = "bold red"

[package]
symbol = "🎁 "

[rust]
symbol = "⚙️ "

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
utc_time_offset = "+1"
time_range = "06:00:00-23:59:59"

[docker_context]
symbol = "🐋 "

```
And I got libxft without bgra. I am on Ubuntu 20.04 and do not 
want to patch it. But other terminal work fine, that is why i am 
a bit disappointed ...
If you have a workaoround, justlet me know.
For the moment, I am not using Starship anymore ... :(( 

Rgds,

**Comment by bakkeby** [comment]
Yes so it does sound like it's the libxft issue.

There's the workaround listed here:
https://git.suckless.org/st/file/FAQ.html#l247

Which you can add in `x.c` around line 1300 (just search for `FcPatternAddBool`) and the starship prompt should work, but all colored emojis are replaced by a small square by the looks of it - so it's not a particularly good solution.

I wonder if other terminals use a different library to render fonts.

**Comment by MrMic** [comment]
For gnome-terminal, here is the dependencies:

```
Package: gnome-terminal
Architecture: amd64
Version: 3.36.1.1-1ubuntu1
Multi-Arch: foreign
Priority: optional
Section: gnome
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 663
Provides: x-terminal-emulator
Depends: libatk1.0-0 (>= 1.12.4), libc6 (>= 2.14), libcairo2 (>= 1.2.4), libdconf1 (>= 0.14.0), libglib2.0-0 (>= 2.50.0), libgtk-3-0 (>= 3.22.27), libpango-1.0-0 (>= 1.14.0), libuuid1 (>= 2.16), libvte-2.91-0 (>= 0.60.1), libx11-6, dconf-gsettings-backend | gsettings-backend, default-dbus-session-bus | dbus-session-bus, python3, python3-gi, gir1.2-glib-2.0, gsettings-desktop-schemas (>= 0.1.0), gnome-terminal-data (>= 3.36), gnome-terminal-data (<< 3.37)

```
