### ISSUE TITLE
How to specify variants of the font?

### ISSUE THREAD

**Issue by UtkarshVerma** [bakkeby/st-flexipatch#80]
How does st look for the bold variants of the font? I want to tell st to use a semibold font instead of the bold one. How do I make st behave like this?

I wrote a fontconfig rule to modify the weight of the bold font to semibold and the rule works in `fc-match`, but st still doesn't pick it up.

**Comment by bakkeby** [comment]
I didn't know this either before I started looking into how st supports bold and italic fonts, but st will ignore any style hints you may be adding as part of the font string. I suppose this may apply to fontconfig rules as well.

In the `xloadfonts` function in x.c we have that st will manipulate the font config pattern to add italic, bold, bold italic and roman.

https://github.com/bakkeby/st-flexipatch/blob/89ced627cdd856837dd849c4032530d980bfa661/x.c#L1337-L1356

I suppose you could try to swap out `FC_WEIGHT_BOLD` with `FC_WEIGHT_SEMIBOLD` here.

Not sure if this is a good reference but found the other weight macros here:
https://code.woboq.org/qt5/include/fontconfig/fontconfig.h.html#_M/FC_WEIGHT_THIN

**Comment by UtkarshVerma** [comment]
Okay. I'll play around with it once I have some free time today. Just a quick discussion though. Don't you think it would make sense for us to allow separate configuration of bold, italic, bold-italic fonts in the config.h? Other terminals allow it, and "Comic Code" (yes, I got it. looks awesome) has a really thick bold variant which I would prefer to avoid.

What is your take on this?

**Comment by bakkeby** [comment]
I suppose that it might be possible to do this, not sure how many people would actually want to do it that way though. You may also want to consider that you can pass in the font string using the `-f` argument which adds complexity as you may want to fall back to the old mechanism in this case.

**Comment by UtkarshVerma** [comment]
I thought about it for some time and decided that things are configurable even now and changing FC_WEIGHT_SEMIBOLD is sufficient. Doing more would only increase complexity without any gains. So I guess this is done.
