### ISSUE TITLE
extract sixel patch

### ISSUE THREAD

**Issue by wael444** [bakkeby/st-flexipatch#90]
hello, is it possible that the sixel patch from this repository (assuming it works), can be extracted for manual patching use?

**Comment by bakkeby** [comment]
You are welcome to try :)

**Comment by speediegq** [comment]
I haven't been able to get the sixel scrollback to work perfectly but I found and updated an old diff. (See top of the patch)

It may have more issues, but it works well enough on my personal st build. [Diff](https://codeberg.org/speedie/patches/raw/branch/master/st-sixel-0.9.diff)

**Comment by wael444** [comment]
the diff you gave contains more than the sixel patch, is it okay if it only contains the sixel patch?

**Comment by wael444** [comment]
> You are welcome to try! :)

![20221202_193513_sc](https://user-images.githubusercontent.com/47404953/205340842-37b8e60b-3d0e-4c53-b9a0-f173b034e652.png)

**Comment by speediegq** [comment]
> the diff you gave contains more than the sixel patch, is it okay if it only contains the sixel patch?

It shouldn't, what extra feature does it contain? If you look at the top of the diff you can see the source of the original diff.

**Comment by wael444** [comment]
considering that i want to use scrollback and scrollback reflow alongside sixel, i think this is gonna be a *HUUUUUUUGE* headache, considering i don't know C.

**Comment by speediegq** [comment]
It doesn't seriously conflict with scrollback in terms of the patch applying but scrolling doesn't move the image. There was an issue here about it a while ago that you might be able to follow.

**Comment by wael444** [comment]
@speediegq thanks for your diff! but, whats with the black borders of the image?

**Comment by speediegq** [comment]
> @speediegq thanks for your diff! but, whats with the black borders of the image?

Don't really know, and it didn't really bother me so I haven't spent much time trying to figure it out.

**Comment by wael444** [comment]
yeah i guess the sixel patch does have some problems, like the image being perfectly still after terminal size change..

**Comment by speediegq** [comment]
It does have issues, sixel really isn't great in my opinion anyway. 

I would tell you to use Ueberzug but the author has deleted that project so until there's a fork, you can either use that old version based on an old commit, w3m which barely works or sixel which doesn't work all that great in most terminal emulators, and images don't look as nice either.

**Comment by wael444** [comment]
>I would tell you to use Ueberzug

I have, i don't think it's very nice and the reference implementation - albeit still really fucking hard, is quite nice as it isn't on a manual Python X11 drawing program.
